# a list of things and use every function
k_c_chiefs = ['Patrick Mahomes', 'Travis Kelce', 'Rashee Rice', 
              'Mecole Hardman', 'Isiah Pacheco', 'Chris Jones', 'George Karloftis']
print(k_c_chiefs)
print(sorted(k_c_chiefs))
print(sorted(k_c_chiefs, reverse=True))
print(f'Adios {k_c_chiefs.pop()}.')
k_c_chiefs.insert(3, 'Mike Danna')
print(k_c_chiefs)
k_c_chiefs.append("L'Jarius Sneed")
print(k_c_chiefs)
k_c_chiefs.remove('Mecole Hardman')
print(k_c_chiefs)
k_c_chiefs.reverse()
print(k_c_chiefs)
k_c_chiefs.sort()
print(k_c_chiefs)
k_c_chiefs.sort(reverse=True)
print(k_c_chiefs)
k_c_chiefs.reverse()
print(k_c_chiefs)
print(f'KC Chiefs Length -> {len(k_c_chiefs)}')
print('Deleting one.')
del(k_c_chiefs[3])
print(f'KC Chiefs Length -> {len(k_c_chiefs)}')
print(k_c_chiefs)